apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ariansvi-resume
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: app/kustomize/overlays/production
    repoURL: https://github.com/ariansvi/ariansvi-resume
    targetRevision: HEAD
    kustomize:
      images:
      - hello-world:latest
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
